---
jupyter:
  jupytext:
    formats: 'ipynb,qmd'
    text_representation:
      extension: .qmd
      format_name: quarto
      format_version: '1.0'
      jupytext_version: 1.14.1
  kernelspec:
    display_name: Python 3 (ipykernel)
    language: python
    name: python3
---

```{python}
from collections import defaultdict
from copy import deepcopy
from pprint import pprint


def read_input(s):
    with open(f"./input/{s}") as f:
        data = f.read().splitlines()
        return data
```

# Day 2



$$sin(x) > cos(x)$$

```{python}
d = read_input("02_input.txt")
print(d[:5])
```

```{python}
def shape_score(s: str) -> int:
    return {
        "A": 1,
        "B": 2,
        "C": 3,
    }[s]


def outcome_score(s1: str, s2: str) -> int:
    if s1 == s2:
        return 3  # draw
    if (s1, s2) in (("A", "B"), ("B", "C"), ("C", "A")):
        return 6  # 2nd player wins
    return 0  # 1st player wins


def round_score(s):
    s1 = s[0]
    s2 = s[2]
    s2 = chr(ord(s2) - 23)
    return shape_score(s2) + outcome_score(s1, s2)


print(sum(round_score(_) for _ in d))
```

## Day 2 - Part 2

```{python}
def strategy(s1: str, s2: str) -> str:
    if s2 == "X":  # loose
        return {
            "B": "A",
            "C": "B",
            "A": "C",
        }[s1]
    if s2 == "Y":  # draw
        return s1
    return {
        "A": "B",
        "B": "C",
        "C": "A",
    }[s1]


def new_round_score(s: str) -> int:
    s1 = s[0]
    s2 = s[2]
    mine = strategy(s1, s2)
    return shape_score(mine) + outcome_score(s1, mine)


# test_data = ["A Y", "B X", "C Z",]
# r = test_data[1]
# print(r)
# print(mine := strategy(r[0], r[2]))
# print(shape_score(mine))
# print(outcome_score(r[0], mine))
# new_round_score(r)

sum(new_round_score(_) for _ in d)
```

# Day 3

One Elf has the important job of loading all of the rucksacks with supplies for the jungle journey. Unfortunately, that Elf didn't quite follow the packing instructions, and so a few items now need to be rearranged.

Each rucksack has two large compartments. All items of a given type are meant to go into exactly one of the two compartments. The Elf that did the packing failed to follow this rule for exactly one item type per rucksack.

The Elves have made a list of all of the items currently in each rucksack (your puzzle input), but they need your help finding the errors. Every item type is identified by a single lowercase or uppercase letter (that is, a and A refer to different types of items).

The list of items for each rucksack is given as characters all on a single line. A given rucksack always has the same number of items in each of its two compartments, so the first half of the characters represent items in the first compartment, while the second half of the characters represent items in the second compartment.

For example, suppose you have the following list of contents from six rucksacks:

vJrwpWtwJgWrhcsFMMfFFhFp  
jqHRNqRjqzjGDLGLrsFMfFZSrLrFZsSL  
PmmdzqPrVvPwwTWBwg  
wMqvLMZHhHMvwLHjbvcjnnSBnvTQFn  
ttgJtRGJQctTZtZT  
CrZsJsPPZsGzwwsLwLmpwMDw  

The first rucksack contains the items vJrwpWtwJgWrhcsFMMfFFhFp, which means its first compartment contains the items vJrwpWtwJgWr, while the second compartment contains the items hcsFMMfFFhFp. The only item type that appears in both compartments is lowercase p.
    
The second rucksack's compartments contain jqHRNqRjqzjGDLGL and rsFMfFZSrLrFZsSL. The only item type that appears in both compartments is uppercase L.
    
The third rucksack's compartments contain PmmdzqPrV and vPwwTWBwg; the only common item type is uppercase P.

The fourth rucksack's compartments only share item type v.

The fifth rucksack's compartments only share item type t.

The sixth rucksack's compartments only share item type s.

To help prioritize item rearrangement, every item type can be converted to a priority:

Lowercase item types a through z have priorities 1 through 26.

Uppercase item types A through Z have priorities 27 through 52.

In the above example, the priority of the item type that appears in both compartments of each rucksack is 16 (p), 38 (L), 42 (P), 22 (v), 20 (t), and 19 (s); the sum of these is 157.

Find the item type that appears in both compartments of each rucksack. What is the sum of the priorities of those item types?

```{python}
print(ord("z") - ord("a") + 1)
ord("Z") - ord("A") + 27
```

```{python}
test_data = [
    "vJrwpWtwJgWrhcsFMMfFFhFp",
    "jqHRNqRjqzjGDLGLrsFMfFZSrLrFZsSL",
    "PmmdzqPrVvPwwTWBwg",
    "wMqvLMZHhHMvwLHjbvcjnnSBnvTQFn",
    "ttgJtRGJQctTZtZT",
    "CrZsJsPPZsGzwwsLwLmpwMDw",
]
test_result = ["p", "L", "P", "v", "t", "s"]
test_score = 157


def common_item(s):
    pivot = int(len(s) / 2)
    assert pivot == len(s[pivot:])
    return set(s[:pivot]).intersection(s[pivot:]).pop()


assert [common_item(r) for r in test_data] == test_result


def priority(c):
    if "a" <= c <= "z":
        return ord(c) - ord("a") + 1
    return ord(c) - ord("A") + 27


assert sum(priority(_) for _ in test_result) == test_score
"preparations done"
```

```{python}
from time import sleep
sleep(5)
data = read_input("03_input.txt")
help(priority)
print(sum(priority(common_item(_)) for _ in data))
```

## Day 3 - Part 2

As you finish identifying the misplaced items, the Elves come to you with another issue.

For safety, the Elves are divided into groups of three. Every Elf carries a badge that identifies their group. For efficiency, within each group of three Elves, the badge is the only item type carried by all three Elves. That is, if a group's badge is item type B, then all three Elves will have item type B somewhere in their rucksack, and at most two of the Elves will be carrying any other item type.

The problem is that someone forgot to put this year's updated authenticity sticker on the badges. All of the badges need to be pulled out of the rucksacks so the new authenticity stickers can be attached.

Additionally, nobody wrote down which item type corresponds to each group's badges. The only way to tell which item type is the right one is by finding the one item type that is common between all three Elves in each group.

Every set of three lines in your list corresponds to a single group, but each group can have a different badge item type. So, in the above example, the first group's rucksacks are the first three lines:

["vJrwpWtwJgWrhcsFMMfFFhFp",
"jqHRNqRjqzjGDLGLrsFMfFZSrLrFZsSL", 
"PmmdzqPrVvPwwTWBwg",]

And the second group's rucksacks are the next three lines:

["wMqvLMZHhHMvwLHjbvcjnnSBnvTQFn",
"ttgJtRGJQctTZtZT",
"CrZsJsPPZsGzwwsLwLmpwMDw",]

In the first group, the only item type that appears in all three rucksacks is lowercase r; this must be their badges. In the second group, their badge item type must be Z.

Priorities for these items must still be found to organize the sticker attachment efforts: here, they are 18 (r) for the first group and 52 (Z) for the second group. The sum of these is 70.

Find the item type that corresponds to the badges of each three-Elf group. What is the sum of the priorities of those item types?

```{python}
test = {}
test[0] = [
    "vJrwpWtwJgWrhcsFMMfFFhFp",
    "jqHRNqRjqzjGDLGLrsFMfFZSrLrFZsSL",
    "PmmdzqPrVvPwwTWBwg",
]
test[1] = [
    "wMqvLMZHhHMvwLHjbvcjnnSBnvTQFn",
    "ttgJtRGJQctTZtZT",
    "CrZsJsPPZsGzwwsLwLmpwMDw",
]

test_badges = ["r", "Z"]


def find_badge(g) -> str:
    return set(g[0]).intersection(g[1]).intersection(g[2]).pop()


assert [find_badge(_) for _ in test.values()] == test_badges
```

```{python}
def chunks(lst, n):
    """Yield successive n-sized chunks from lst."""
    for i in range(0, len(lst), n):
        yield lst[i : i + n]


sum(priority(_) for _ in (find_badge(_) for _ in chunks(data, 3)))
```

# Day 4

Space needs to be cleared before the last supplies can be unloaded from the ships, and so several Elves have been assigned the job of cleaning up sections of the camp. Every section has a unique ID number, and each Elf is assigned a range of section IDs.

However, as some of the Elves compare their section assignments with each other, they've noticed that many of the assignments overlap. To try to quickly find overlaps and reduce duplicated effort, the Elves pair up and make a big list of the section assignments for each pair (your puzzle input).

For example, consider the following list of section assignment pairs:

```
2-4,6-8
2-3,4-5
5-7,7-9
2-8,3-7
6-6,4-6
2-6,4-8
```

For the first few pairs, this list means:

Within the first pair of Elves, the first Elf was assigned sections 2-4 (sections 2, 3, and 4), while the second Elf was assigned sections 6-8 (sections 6, 7, 8).

The Elves in the second pair were each assigned two sections.

The Elves in the third pair were each assigned three sections: one got sections 5, 6, and 7, while the other also got 7, plus 8 and 9.

This example list uses single-digit section IDs to make it easier to draw; your actual list might contain larger numbers. Visually, these pairs of section assignments look like this:

```
.234.....  2-4
.....678.  6-8

.23......  2-3
...45....  4-5

....567..  5-7
......789  7-9

.2345678.  2-8
..34567..  3-7

.....6...  6-6
...456...  4-6

.23456...  2-6
...45678.  4-8
```

Some of the pairs have noticed that one of their assignments fully contains the other. For example, 2-8 fully contains 3-7, and 6-6 is fully contained by 4-6. In pairs where one assignment fully contains the other, one Elf in the pair would be exclusively cleaning sections their partner will already be cleaning, so these seem like the most in need of reconsideration. In this example, there are 2 such pairs.

In how many assignment pairs does one range fully contain the other?

```{python}
test_data = """2-4,6-8
2-3,4-5
5-7,7-9
2-8,3-7
6-6,4-6
2-6,4-8""".split(
    "\n"
)

test_result = 2


def includes(a1, a2, b1, b2) -> bool:
    if a1 <= b1 and b2 <= a2:
        return True
    return b1 <= a1 and a2 <= b2


def process_row(r, fnc=includes) -> bool:
    # print(r)
    lhs, rhs = r.split(",")
    l1, l2 = map(int, lhs.split("-"))
    r1, r2 = map(int, rhs.split("-"))
    return fnc(l1, l2, r1, r2)


assert sum(process_row(r) for r in test_data) == test_result
```

```{python}
data = read_input("04_input.txt")
sum(process_row(r) for r in data)
```

## Day 4 - Part 2

It seems like there is still quite a bit of duplicate work planned. Instead, the Elves would like to know the number of pairs that overlap at all.

In the above example, the first two pairs (2-4,6-8 and 2-3,4-5) don't overlap, while the remaining four pairs (5-7,7-9, 2-8,3-7, 6-6,4-6, and 2-6,4-8) do overlap:

5-7,7-9 overlaps in a single section, 7.

2-8,3-7 overlaps all of the sections 3 through 7.

6-6,4-6 overlaps in a single section, 6.

2-6,4-8 overlaps in sections 4, 5, and 6.

So, in this example, the number of overlapping assignment pairs is 4.

In how many assignment pairs do the ranges overlap?

```{python}
test_overlap = 4


def overlap(a1, a2, b1, b2) -> bool:
    return not (a2 < b1 or b2 < a1)


assert sum(process_row(r, fnc=overlap) for r in test_data) == 4
```

```{python}
sum(process_row(r, fnc=overlap) for r in data)
```

# Day 5

The expedition can depart as soon as the final supplies have been unloaded from the ships. Supplies are stored in stacks of marked crates, but because the needed supplies are buried under many other crates, the crates need to be rearranged.

The ship has a giant cargo crane capable of moving crates between stacks. To ensure none of the crates get crushed or fall over, the crane operator will rearrange them in a series of carefully-planned steps. After the crates are rearranged, the desired crates will be at the top of each stack.

The Elves don't want to interrupt the crane operator during this delicate procedure, but they forgot to ask her which crate will end up where, and they want to be ready to unload them as soon as possible so they can embark.

They do, however, have a drawing of the starting stacks of crates and the rearrangement procedure (your puzzle input). For example:

```
    [D]    
[N] [C]    
[Z] [M] [P]
 1   2   3 
```

```
move 1 from 2 to 1
move 3 from 1 to 3
move 2 from 2 to 1
move 1 from 1 to 2
```

In this example, there are three stacks of crates. Stack 1 contains two crates: crate Z is on the bottom, and crate N is on top. Stack 2 contains three crates; from bottom to top, they are crates M, C, and D. Finally, stack 3 contains a single crate, P.

Then, the rearrangement procedure is given. In each step of the procedure, a quantity of crates is moved from one stack to a different stack. In the first step of the above rearrangement procedure, one crate is moved from stack 2 to stack 1, resulting in this configuration:

```
[D]        
[N] [C]    
[Z] [M] [P]
 1   2   3 
```

In the second step, three crates are moved from stack 1 to stack 3. Crates are moved one at a time, so the first crate to be moved (D) ends up below the second and third crates:


```
        [Z]
        [N]
    [C] [D]
    [M] [P]
 1   2   3
```

Then, both crates are moved from stack 2 to stack 1. Again, because crates are moved one at a time, crate C ends up below crate M:

```
        [Z]
        [N]
[M]     [D]
[C]     [P]
 1   2   3
```

Finally, one crate is moved from stack 1 to stack 2:

```
        [Z]
        [N]
        [D]
[C] [M] [P]
 1   2   3
```

The Elves just need to know which crate will end up on top of each stack; in this example, the top crates are C in stack 1, M in stack 2, and Z in stack 3, so you should combine these together and give the Elves the message CMZ.

After the rearrangement procedure completes, what crate ends up on top of each stack?

```{python}
test_input = """    [D]    
[N] [C]    
[Z] [M] [P]
 1   2   3 

move 1 from 2 to 1
move 3 from 1 to 3
move 2 from 2 to 1
move 1 from 1 to 2
""".split(
    "\n"
)

# print(test_input)


def split_stacks_moves(input):
    stacks = []
    for i, row in enumerate(input):
        # print(i, "X", row, "X")
        if row == "":
            break
        stacks.append(row)
    return stacks, [_ for _ in input[i:] if _ != ""]


stacks_input, moves_input = split_stacks_moves(test_input)
assert len(stacks_input) == 4
assert len(moves_input) == 4

from collections import defaultdict


def parse_stacks(stacks_input):
    stacks = defaultdict(list)
    cols = max(map(int, colrow := stacks_input.pop().split()))
    # print(f"found {cols} stacks ({colrow})")
    while stacks_input:
        row = stacks_input.pop()
        # print(row)
        for i in range(maxi := min(cols, int((len(row) - 1) / 4)) + 1):
            # print(maxi,cols)
            letter = row[1 + i * 4]
            if letter != " ":
                # print(i+1, letter)
                stacks[i + 1] += letter
        # pprint(dict(stacks))
    return stacks


parsed_stacks = parse_stacks(stacks_input)
assert parsed_stacks == {1: [*"ZN"], 2: [*"MCD"], 3: ["P"]}


def parse_moves(moves):
    result = []
    for row in moves:
        _, qty, _, fr, _, to = row.split()
        result.append(Move(int(fr), int(to), int(qty)))
    return result


from dataclasses import dataclass


@dataclass
class Move:
    fr: int
    to: int
    qty: int


# pprint(moves_input)
parsed_moves = parse_moves(moves_input)
assert parsed_moves == [
    Move(2, 1, 1),
    Move(1, 3, 3),
    Move(2, 1, 2),
    Move(1, 2, 1),
]


def apply_moves(stacks_in, moves):
    stacks = stacks_in.copy()
    for step, m in enumerate(moves):
        # print("---", m)
        for _ in range(m.qty):
            try:
                stacks[m.to].append(stacks[m.fr].pop())
            except:
                pprint(stacks)
                pprint(m)
                print(f"Problem in step {step}")
                raise ValueError("can't work with this data")
        # pprint(dict(stacks))
    return stacks


pprint(dict(parsed_stacks))
moved_stacks = apply_moves(parsed_stacks, parsed_moves)
pprint(dict(moved_stacks))
assert dict(moved_stacks) == {
    1: ["C"],
    2: ["M"],
    3: [*"PDNZ"],
}


def combined_tops(stacks):
    return "".join(_[-1] for _ in stacks.values())


assert combined_tops(moved_stacks) == "CMZ"


def day5(input_data, apply_moves=apply_moves):
    stacks_input, moves_input = split_stacks_moves(input_data)
    # print(f"Input slitted. {len(stacks_input)} lines of stack data, {len(moves_input)} lines of move data")
    # print("====")
    # pprint(stacks_input)
    parsed_stacks = parse_stacks(stacks_input)
    # print("=================")
    # pprint(dict(parsed_stacks))
    # print(f"Stack data parsed. There are {max(parsed_stacks.keys())} stacks.")
    parsed_moves = parse_moves(moves_input)
    moved_stacks = apply_moves(parsed_stacks, parsed_moves)
    return combined_tops(moved_stacks)


assert day5(test_input) == "CMZ"
"success!"
```

```{python}
data = read_input("05_input.txt")
print(data[:3])
day5(data)  # 'FRDSQRRCD'
```

## Day 5 - Part 2

As you watch the crane operator expertly rearrange the crates, you notice the process isn't following your prediction.

Some mud was covering the writing on the side of the crane, and you quickly wipe it away. The crane isn't a CrateMover 9000 - it's a CrateMover 9001.

The CrateMover 9001 is notable for many new and exciting features: air conditioning, leather seats, an extra cup holder, and the ability to pick up and move multiple crates at once.

Again considering the example above, the crates begin in the same configuration:
```
    [D]    
[N] [C]    
[Z] [M] [P]
 1   2   3 
```

Moving a single crate from stack 2 to stack 1 behaves the same as before:

```
[D]        
[N] [C]    
[Z] [M] [P]
 1   2   3 
```

However, the action of moving three crates from stack 1 to stack 3 means that those three moved crates stay in the same order, resulting in this new configuration:

```
        [D]
        [N]
    [C] [Z]
    [M] [P]
 1   2   3
```

Next, as both crates are moved from stack 2 to stack 1, they retain their order as well:

```
        [D]
        [N]
[C]     [Z]
[M]     [P]
 1   2   3
```

Finally, a single crate is still moved from stack 1 to stack 2, but now it's crate C that gets moved:

```
        [D]
        [N]
        [Z]
[M] [C] [P]
 1   2   3
```

In this example, the CrateMover 9001 has put the crates in a totally different order: MCD.

Before the rearrangement process finishes, update your simulation so that the Elves know where they should stand to be ready to unload the final supplies. After the rearrangement procedure completes, what crate ends up on top of each stack?

```{python}
stacks = {}
stacks[7] = ["W", "F", "R", "L", "C", "T", "S", "V"]
stacks[8] = ["T", "Z", "N"]
stacks[9] = ["M", "S", "D", "J", "R", "Q", "H", "N"]
m = Move(fr=9, to=8, qty=6)
pprint(stacks)
stacks[m.to] += stacks[m.fr][-m.qty :]
pprint(stacks)
stacks[m.fr] = stacks[m.fr][: -m.qty]
pprint(stacks)
```

```{python}
def moves_9001(stacks_in, moves):
    stacks = stacks_in.copy()
    for step, m in enumerate(moves):
        # print("---", m)
        try:
            stacks[m.to] += stacks[m.fr][-m.qty :]
            stacks[m.fr] = stacks[m.fr][: -m.qty]
        except:
            pprint(stacks)
            pprint(m)
            print(f"Problem in step {step}")
            raise ValueError("can't work with this data")
        # pprint(dict(stacks))
    return stacks


assert day5(test_input, apply_moves=moves_9001) == "MCD"
```

```{python}
day5(data, apply_moves=moves_9001)
```

# Day 6 -- Tuning Trouble --

The preparations are finally complete; you and the Elves leave camp on foot and begin to make your way toward the star fruit grove.

As you move through the dense undergrowth, one of the Elves gives you a handheld device. He says that it has many fancy features, but the most important one to set up right now is the communication system.

However, because he's heard you have significant experience dealing with signal-based systems, he convinced the other Elves that it would be okay to give you their one malfunctioning device - surely you'll have no problem fixing it.

As if inspired by comedic timing, the device emits a few colorful sparks.

To be able to communicate with the Elves, the device needs to lock on to their signal. The signal is a series of seemingly-random characters that the device receives one at a time.

To fix the communication system, you need to add a subroutine to the device that detects a start-of-packet marker in the datastream. In the protocol being used by the Elves, the start of a packet is indicated by a sequence of four characters that are all different.

The device will send your subroutine a datastream buffer (your puzzle input); your subroutine needs to identify the first position where the four most recently received characters were all different. Specifically, it needs to report the number of characters from the beginning of the buffer to the end of the first such four-character marker.

For example, suppose you receive the following datastream buffer:

`mjqjpqmgbljsphdztnvjfqwrcgsmlb`

After the first three characters (mjq) have been received, there haven't been enough characters received yet to find the marker. The first time a marker could occur is after the fourth character is received, making the most recent four characters mjqj. Because j is repeated, this isn't a marker.

The first time a marker appears is after the seventh character arrives. Once it does, the last four characters received are jpqm, which are all different. In this case, your subroutine should report the value 7, because the first start-of-packet marker is complete after 7 characters have been processed.

Here are a few more examples:

```
    bvwbjplbgvbhsrlpgdmjqwftvncz: first marker after character 5
    nppdvjthqldpwncqszvftbrmjlhg: first marker after character 6
    nznrnfrfntjfmvfwmzdfjlvtqnbhcprsg: first marker after character 10
    zcfzfwzzqfrljwzlrfnpqdbhtmscgvjw: first marker after character 11
```


How many characters need to be processed before the first start-of-packet marker is detected?

```{python}
examples = [
    ("bvwbjplbgvbhsrlpgdmjqwftvncz", "5"),
    ("nppdvjthqldpwncqszvftbrmjlhg", "6"),
    ("nznrnfrfntjfmvfwmzdfjlvtqnbhcprsg", "10"),
    ("zcfzfwzzqfrljwzlrfnpqdbhtmscgvjw", "11"),
]

s, c = examples[0]


def find_marker(s, n=4):
    for i in range(n, len(s)):
        # print(t:=s[i-n:i], len(t), len(set(t)))
        if len(set(s[i - n : i])) == n:
            return i
    raise ValueError(f"no {n} distinct chars in {s}")


for s, c in examples:
    # print(find_marker(s), c, find_marker(s) == c)
    assert find_marker(s) == int(c)

"success"
```

```{python}
data = read_input("06_input.txt")
# print(data)
find_marker(data[0])
```

## Day 6 - Part 2

Your device's communication system is correctly detecting packets, but still isn't working. It looks like it also needs to look for messages.

A start-of-message marker is just like a start-of-packet marker, except it consists of 14 distinct characters rather than 4.

Here are the first positions of start-of-message markers for all of the above examples:

```
    mjqjpqmgbljsphdztnvjfqwrcgsmlb: first marker after character 19
    bvwbjplbgvbhsrlpgdmjqwftvncz: first marker after character 23
    nppdvjthqldpwncqszvftbrmjlhg: first marker after character 23
    nznrnfrfntjfmvfwmzdfjlvtqnbhcprsg: first marker after character 29
    zcfzfwzzqfrljwzlrfnpqdbhtmscgvjw: first marker after character 26
```

How many characters need to be processed before the first start-of-message marker is detected?

```{python}
test_input = [
    _.strip()
    for _ in """mjqjpqmgbljsphdztnvjfqwrcgsmlb: first marker after character 19
    bvwbjplbgvbhsrlpgdmjqwftvncz: first marker after character 23
    nppdvjthqldpwncqszvftbrmjlhg: first marker after character 23
    nznrnfrfntjfmvfwmzdfjlvtqnbhcprsg: first marker after character 29
    zcfzfwzzqfrljwzlrfnpqdbhtmscgvjw: first marker after character 26""".splitlines()
]

examples = [(_.split(":")[0], int(_.split()[-1])) for _ in test_input]

# print(test_input)
pprint(examples)

for (s, c) in examples:
    assert find_marker(s, n=14) == c
```

```{python}
#| tags: []
find_marker(data[0], 14)
```

# Day 7

You can hear birds chirping and raindrops hitting leaves as the expedition proceeds. Occasionally, you can even hear much louder sounds in the distance; how big do the animals get out here, anyway?

The device the Elves gave you has problems with more than just its communication system. You try to run a system update:

```
$ system-update --please --pretty-please-with-sugar-on-top
Error: No space left on device
```

Perhaps you can delete some files to make space for the update?

You browse around the filesystem to assess the situation and save the resulting terminal output (your puzzle input). For example:

```
$ cd /
$ ls
dir a
14848514 b.txt
8504156 c.dat
dir d
$ cd a
$ ls
dir e
29116 f
2557 g
62596 h.lst
$ cd e
$ ls
584 i
$ cd ..
$ cd ..
$ cd d
$ ls
4060174 j
8033020 d.log
5626152 d.ext
7214296 k
```
The filesystem consists of a tree of files (plain data) and directories (which can contain other directories or files). The outermost directory is called /. You can navigate around the filesystem, moving into or out of directories and listing the contents of the directory you're currently in.

Within the terminal output, lines that begin with $ are commands you executed, very much like some modern computers:

- cd means change directory. This changes which directory is the current directory, but the specific result depends on the argument:
    - cd x moves in one level: it looks in the current directory for the directory named x and makes it the current directory.
    - cd .. moves out one level: it finds the directory that contains the current directory, then makes that directory the current directory.
    - cd / switches the current directory to the outermost directory, /.
- ls means list. It prints out all of the files and directories immediately contained by the current directory:
    - 123 abc means that the current directory contains a file named abc with size 123.
    - dir xyz means that the current directory contains a directory named xyz.

Given the commands and output in the example above, you can determine that the filesystem looks visually like this:

```
- / (dir)
  - a (dir)
    - e (dir)
      - i (file, size=584)
    - f (file, size=29116)
    - g (file, size=2557)
    - h.lst (file, size=62596)
  - b.txt (file, size=14848514)
  - c.dat (file, size=8504156)
  - d (dir)
    - j (file, size=4060174)
    - d.log (file, size=8033020)
    - d.ext (file, size=5626152)
    - k (file, size=7214296)
```

Here, there are four directories: / (the outermost directory), a and d (which are in /), and e (which is in a). These directories also contain files of various sizes.

Since the disk is full, your first step should probably be to find directories that are good candidates for deletion. To do this, you need to determine the total size of each directory. The total size of a directory is the sum of the sizes of the files it contains, directly or indirectly. (Directories themselves do not count as having any intrinsic size.)

The total sizes of the directories above can be found as follows:

- The total size of directory e is 584 because it contains a single file i of size 584 and no other directories.
- The directory a has total size 94853 because it contains files f (size 29116), g (size 2557), and h.lst (size 62596), plus file i indirectly (a contains e which contains i).
- Directory d has total size 24933642.
- As the outermost directory, / contains every file. Its total size is 48381165, the sum of the size of every file.

To begin, find all of the directories with a total size of at most 100000, then calculate the sum of their total sizes. In the example above, these directories are a and e; the sum of their total sizes is 95437 (94853 + 584). (As in this example, this process can count files more than once!)



```{python}
test_input = """$ cd /
$ ls
dir a
14848514 b.txt
8504156 c.dat
dir d
$ cd a
$ ls
dir e
29116 f
2557 g
62596 h.lst
$ cd e
$ ls
584 i
$ cd ..
$ cd ..
$ cd d
$ ls
4060174 j
8033020 d.log
5626152 d.ext
7214296 k""".splitlines()

def totalsize(input):
    sizes = [_ for _ in input if _[0] in "0123456789]"]
    return sum(int(_.split()[0]) for _ in sizes)

def dir_sizes(input):
    dirs = [_.split()[1] for _ in input if _[:4] == "dir "]
    sizes = defaultdict(int)
    indirs = []
    curdir = ""
    for row in input:
        if row[:4] == "$ cd":
            cdir = row.split()[-1]
            if cdir == "..":
                cdir = indirs.pop()
                curdir = "/".join(indirs)
                print("exiting", cdir, curdir, indirs)
            else:
                indirs.append(cdir)
                curdir = "/".join(indirs)
                print("entering", cdir, curdir, indirs)
                if curdir in sizes.keys():
                    raise ValueError(f"{curdir} has been processed already")
            continue
        if row[0] in "0123456789":
            size, file = row.split()
            # print(f"{file} ({size})")
            for d in range(len(indirs)):
                sizes["/".join(indirs[:d+1])] += int(size)
            pprint(dict(sizes))
            continue
        if row[:4] == "dir ":
            continue
        if row == "$ ls":
            continue
        raise ValueError(f"unprocessable entry {row}")
    return dict(sizes)


pprint(result_sizes:=dir_sizes(test_input))
assert result_sizes == {'/': 48381165, '//a': 94853, '//d': 24933642, '//a/e': 584}

def sum_small_dirs(dirs, maxsize):
    return sum(_ for _ in dirs.values() if _ < maxsize)

assert sum_small_dirs(result_sizes, 100000) == 95437

```

```{python}
data = read_input("07_input.txt")
sizes = dir_sizes(data)
pprint(sizes)

print(sum_small_dirs(sizes, 100_000))
```

## Day 7 - Part 2

Now, you're ready to choose a directory to delete.

The total disk space available to the filesystem is 70000000. To run the update, you need unused space of at least 30000000. You need to find a directory you can delete that will free up enough space to run the update.

In the example above, the total size of the outermost directory (and thus the total amount of used space) is 48381165; this means that the size of the unused space must currently be 21618835, which isn't quite the 30000000 required by the update. Therefore, the update still requires a directory with total size of at least 8381165 to be deleted before it can run.

To achieve this, you have the following options:

- Delete directory e, which would increase unused space by 584.
- Delete directory a, which would increase unused space by 94853.
- Delete directory d, which would increase unused space by 24933642.
- Delete directory /, which would increase unused space by 48381165.

Directories e and a are both too small; deleting them would not free up enough space. However, directories d and / are both big enough! Between these, choose the smallest: d, increasing unused space by 24933642.

Find the smallest directory that, if deleted, would free up enough space on the filesystem to run the update. What is the total size of that directory?


```{python}

required_size = 30000000 - (70000000 - sizes["/"])
print(f"we need to find {required_size}")

candidates=[(d, size) for (d,size) in sizes.items() if size >= required_size]
pprint(sorted(candidates, key=lambda x: x[1])[0])

```

# Day 8

```{python}
test_input="""30373
25512
65332
33549
35390""".splitlines()

def build_grid(input):
    return [
    [int(_) for _ in row]
    for row in input
]

grid = build_grid(test_input)


def check_grid(grid):
    width = len(grid[0])
    assert all(len(_)== width for _ in grid)
    print(width, len(grid))

check_grid(grid)

def get_line(grid, index: int, row=True, direction=True):
    if row:
        line = grid[index]
    else:
        line = [_[index] for _ in grid]
    if direction:
        return line
    return line[::-1]

pprint(grid)
pprint(get_line(grid, 0))
assert get_line(grid, 0) ==  [3, 0, 3, 7, 3]
pprint(get_line(grid, 0, row=False))
assert get_line(grid, 0, row=False) ==  [3, 2, 6, 3, 3]

def is_visible_line(index, line):
    if index in [0, len(line) - 1]:
        return True
    result = (
        (r1:=max(line[0:index]) < line[index])
    or
        (r2:=max(line[index+1:]) < line[index])
    )
    # print(r1)
    return result

assert is_visible_line(0, [3, 0, 3, 7, 3])
assert is_visible_line(4, [3, 0, 3, 7, 3])

assert is_visible_line(2, [2, 5, 5, 1, 2])
assert not is_visible_line(3, [2, 5, 5, 1, 2])

def count_visible(grid):
    count = 0
    for i in range(len(grid[0])):
        for j in range(len(grid)):
            # print(i,j)
            if is_visible_line(i, get_line(grid, j)) or is_visible_line(j, get_line(grid, i, row=False)):
                count += 1
    return count

print(count_visible(grid))
assert count_visible(grid) == 21

```

```{python}
data = read_input("08_input.txt")

grid = build_grid(data)
check_grid(grid)
count_visible(grid)
```

## Day 8 - Part 2

```{python}

test_grid = build_grid(test_input)


def scenic_segment(segment):
    height = segment[0]
    # print(segment, height)
    count = 0
    for _ in segment[1:]:
        count += 1
        # print(_)
        if _ >= height:
            break
    # print(count)
    return count

assert scenic_segment([5, 1, 2]) == 2
assert scenic_segment([5]) == 0
assert scenic_segment([5, 1, 2, 5, 3]) == 3
assert scenic_segment([5, 1, 2, 7, 6]) == 3
assert scenic_segment([5, 1, 2, 7, 10]) == 3


def scenic_score(grid, i, j):
    row = get_line(grid, i)
    # print("left", row[:j+1])
    left = scenic_segment(row[:j+1][::-1])
    right = scenic_segment(row[j:])
    col = get_line(grid, j, row=False)
    up = scenic_segment(col[:i+1][::-1])
    down = scenic_segment(col[i:])
    # print(up, left, right, down)
    return up * left * right * down

assert scenic_score(test_grid, 1, 2) == 4
assert scenic_score(test_grid, 3, 2) == 8

from itertools import product
def max_scenic(grid):
    # print(list(product(range(len(grid[0])), range(len(grid)))))
    return max(scenic_score(grid, i, j)
        for (i,j) in product(range(len(grid[0])), range(len(grid)))
    )

assert max_scenic(test_grid) == 8

print(max_scenic(grid))
```


# Day 9

This rope bridge creaks as you walk along it. You aren't sure how old it is, or whether it can even support your weight.

It seems to support the Elves just fine, though. The bridge spans a gorge which was carved out by the massive river far below you.

You step carefully; as you do, the ropes stretch and twist. You decide to distract yourself by modeling rope physics; maybe you can even figure out where not to step.

Consider a rope with a knot at each end; these knots mark the head and the tail of the rope. If the head moves far enough away from the tail, the tail is pulled toward the head.

Due to nebulous reasoning involving Planck lengths, you should be able to model the positions of the knots on a two-dimensional grid. Then, by following a hypothetical series of motions (your puzzle input) for the head, you can determine how the tail will move.

Due to the aforementioned Planck lengths, the rope must be quite short; in fact, the head (H) and tail (T) must always be touching (diagonally adjacent and even overlapping both count as touching):

```
....
.TH.
....

....
.H..
..T.
....

...
.H. (H covers T)
...
```

If the head is ever two steps directly up, down, left, or right from the tail, the tail must also move one step in that direction so it remains close enough:

```
.....    .....    .....
.TH.. -> .T.H. -> ..TH.
.....    .....    .....

...    ...    ...
.T.    .T.    ...
.H. -> ... -> .T.
...    .H.    .H.
...    ...    ...
```

Otherwise, if the head and tail aren't touching and aren't in the same row or column, the tail always moves one step diagonally to keep up:


```
.....    .....    .....
.....    ..H..    ..H..
..H.. -> ..... -> ..T..
.T...    .T...    .....
.....    .....    .....

.....    .....    .....
.....    .....    .....
..H.. -> ...H. -> ..TH.
.T...    .T...    .....
.....    .....    .....
```

You just need to work out where the tail goes as the head follows a series of motions. Assume the head and the tail both start at the same position, overlapping.

For example:

```{python}

test_moves = """R 4
U 4
L 3
D 1
R 4
D 1
L 5
R 2""".splitlines()
```

This series of motions moves the head right four steps, then up four steps, then left three steps, then down one step, and so on. After each step, you'll need to update the position of the tail if the step means the head is no longer adjacent to the tail. Visually, these motions occur as follows (s marks the starting position as a reference point):

== Initial State ==

```
......
......
......
......
H.....  (H covers T, s)
```

== R 4 ==

```
......
......
......
......
TH....  (T covers s)

......
......
......
......
sTH...

......
......
......
......
s.TH..

......
......
......
......
s..TH.


== U 4 ==

......
......
......
....H.
s..T..

......
......
....H.
....T.
s.....

......
....H.
....T.
......
s.....

....H.
....T.
......
......
s.....

== L 3 ==

...H..
....T.
......
......
s.....

..HT..
......
......
......
s.....

.HT...
......
......
......
s.....

== D 1 ==

..T...
.H....
......
......
s.....

== R 4 ==

..T...
..H...
......
......
s.....

..T...
...H..
......
......
s.....

......
...TH.
......
......
s.....

......
....TH
......
......
s.....

== D 1 ==

......
....T.
.....H
......
s.....

== L 5 ==

......
....T.
....H.
......
s.....

......
....T.
...H..
......
s.....

......
......
..HT..
......
s.....

......
......
.HT...
......
s.....

......
......
HT....
......
s.....

== R 2 ==

......
......
.H....  (H covers T)
......
s.....

......
......
.TH...
......
s.....
```

After simulating the rope, you can count up all of the positions the tail visited at least once. In this diagram, s again marks the starting position (which the tail also visited) and # marks other positions the tail visited:

```
..##..
...##.
.####.
....#.
s###..
```

So, there are 13 positions the tail visited at least once.

Simulate your complete hypothetical series of motions. How many positions does the tail of the rope visit at least once?


```{python}


def print_grid(grid):
    for (i, row) in enumerate(grid):
        print(f"{i:2d}", ''.join(row))
def move_head(head_pos, direction):
    # print("H", head_pos)
    if direction == 'U':
        head_pos[0] -= 1
    elif direction == 'D':
        head_pos[0] += 1
    elif direction == 'L':
        head_pos[1] -= 1
    elif direction == 'R':
        head_pos[1] += 1
    return head_pos

def sign(x):
    return (x > 0) - (x < 0)

def tail_follows(head_pos, tail_pos):
    for i in range(2):
        j = 1 - i
        if abs(d1:=head_pos[j] - tail_pos[j]) >= 2:
            if (d:=head_pos[i] - tail_pos[i]) != 0:
                tail_pos[i] += sign(d)
            tail_pos[j] += sign(d1)
    return tail_pos

def one_move(head_pos, tail_pos, move):
    visited_positions = set()
    direction, distance = move
    for _ in range(distance):
        head_pos = move_head(head_pos, direction)
        tail_pos = tail_follows(head_pos, tail_pos)
        # print(f"Step {_}")
        visited_positions.add(tuple(tail_pos))
    return head_pos, tail_pos, visited_positions

def process_chain(moves, knots=10, grid=False, width=30, height=30, start_x = 15, start_y=12):

    def pgrid():
        grid = deepcopy(empty_grid)
        for (k, pos) in positions.items():
            # print("Draw", k,pos)
            if k == knots -1:
                k="T"
            if k == 0:
                k="H"
            grid[pos[0]][pos[1]] = str(k)
        print_grid(grid)
    start_pos = [start_y, start_x]
    if grid:
        empty_grid = [["." for _ in range(width)] for _ in range(height)]
    positions = {_: start_pos.copy() for _ in range(knots)}
    visited_positions = set()
    for (i, move) in enumerate(moves):
        print("==================================")
        print(f"{i}/{len(moves)-1}", move, positions)
        direction, distance = move
        for _ in range(distance):
            print("Step", _)
            # pprint(positions)
            positions[0] = move_head(positions[0], direction)
            for i in range(1, knots):
                positions[i] = tail_follows(positions[i-1], positions[i])
            visited_positions.add(tuple(positions[knots - 1]))
        # grid[head_pos[0]][head_pos[1]] = 'H'
        # grid[tail_pos[0]][tail_pos[1]] = 'T'
        # print_grid(grid)
        # print(len(grid))
        # add the tail's position to the set of visited positions
        
        # update the grid with the new positions of the head and tail
            if grid:
                pgrid()    
    # return the final grid and the number of visited positions
    pprint(visited_positions)
    return len(visited_positions)

def process_moves(moves, width=6, height=5):
    # create a grid to represent the rope and its knots
    # grid = [['.' for _ in range(width)] for _ in range(height)]
    grid = ["."]
    # initialize the positions of the head and tail
    head_pos = [height - 1, 0]
    tail_pos = [height - 1, 0]
    # keep track of the positions visited by the tail
    visited_positions = set()
    
    # iterate through the series of moves
    for (i, move) in enumerate(moves):
        print(f"{i}/{len(moves)-1}", move, head_pos, tail_pos)
        head_pos, tail_pos, new_positions = one_move(head_pos, tail_pos, move)
        visited_positions |= new_positions
        # grid[head_pos[0]][head_pos[1]] = 'H'
        # grid[tail_pos[0]][tail_pos[1]] = 'T'
        # print_grid(grid)
        # print(len(grid))
        # add the tail's position to the set of visited positions
        
        # update the grid with the new positions of the head and tail
    
    # return the final grid and the number of visited positions
    return grid, len(visited_positions)

def extract_moves(input):
    return [((p:=_.split())[0], int(p[1])) for _ in input] 

moves = extract_moves(test_moves2)
print(moves)
positions = process_chain(moves[:10], knots=10, grid=True, width=30, height=30, start_x=15, start_y=15)
# print_grid(grid)
print(f"visited {positions} positions")  # 13 or 36 for test_moves2
```

```{python}
data = read_input("09_input.txt")
moves = extract_moves(data)
positions = process_chain(moves, knots=10, grid=False, width=100, height=100, start_x=50, start_y=50)
# print_grid(grid)
print(f"visited {positions} positions")  # 2455

```

## Day 9 - Part 2

```{python}

test_moves2 = """R 5
U 8
L 8
D 3
R 17
D 10
L 25
U 20""".splitlines()


moves = extract_moves(test_moves2)

def process_chain(moves, knots=10, grid=False):

    def pgrid():
        grid = deepcopy(empty_grid)
        for (k, pos) in positions.items():
            # print("Draw", k,pos)
            grid[pos[0]][pos[1]] = str(k)
        print_grid(grid)
    width = 30
    height = 30
    start_pos = [15, 12]
    if grid:
        empty_grid = [["." for _ in range(width)] for _ in range(height)]
    positions = {_: start_pos.copy() for _ in range(knots)}
    visited_positions = set()
    for (i, move) in enumerate(moves):
        print("==================================")
        print(f"{i}/{len(moves)-1}", move, positions)
        direction, distance = move
        for _ in range(distance):
            print("Step", _)
            # pprint(positions)
            positions[0] = move_head(positions[0], direction)
            for i in range(1, knots):
                positions[i] = tail_follows(positions[i-1], positions[i])
            visited_positions.add(tuple(positions[knots - 1]))
        # grid[head_pos[0]][head_pos[1]] = 'H'
        # grid[tail_pos[0]][tail_pos[1]] = 'T'
        # print_grid(grid)
        # print(len(grid))
        # add the tail's position to the set of visited positions
        
        # update the grid with the new positions of the head and tail
            if grid:
                pgrid()    
    # return the final grid and the number of visited positions
    pprint(visited_positions)
    return len(visited_positions)

print(moves)
print(f"Visited {process_chain(moves[:3], grid=False)} positions")
moves = extract_moves(data)
print(f"Visited {process_chain(moves)} positions")  # 2455

```

# Day 10

```{python}
test_input = """noop
addx 3
addx -5""".splitlines()

durations = {
    "noop": 1,
    "addx": 2,
}

def parse(line):
    if line == "noop":
        return durations["noop"], 0
    ins, val = line.split()
    return durations[ins], int(val)


def create_graph(data):
    graph = {}
    cycle = 1
    value = 1
    for line in data:
        duration, val = parse(line)
        for _ in range(duration):
            graph[cycle] = value
            cycle += 1
        value += val
    graph[cycle] = value
    return graph

graph = create_graph(test_input) 
pprint(graph)
assert graph[1] == 1
assert graph[2] == 1
assert graph[3] == 1
assert graph[4] == 4
assert graph[5] == 4
assert graph[6] == -1

test_input2 = """addx 15
addx -11
addx 6
addx -3
addx 5
addx -1
addx -8
addx 13
addx 4
noop
addx -1
addx 5
addx -1
addx 5
addx -1
addx 5
addx -1
addx 5
addx -1
addx -35
addx 1
addx 24
addx -19
addx 1
addx 16
addx -11
noop
noop
addx 21
addx -15
noop
noop
addx -3
addx 9
addx 1
addx -3
addx 8
addx 1
addx 5
noop
noop
noop
noop
noop
addx -36
noop
addx 1
addx 7
noop
noop
noop
addx 2
addx 6
noop
noop
noop
noop
noop
addx 1
noop
noop
addx 7
addx 1
noop
addx -13
addx 13
addx 7
noop
addx 1
addx -33
noop
noop
noop
addx 2
noop
noop
noop
addx 8
noop
addx -1
addx 2
addx 1
noop
addx 17
addx -9
addx 1
addx 1
addx -3
addx 11
noop
noop
addx 1
noop
addx 1
noop
noop
addx -13
addx -19
addx 1
addx 3
addx 26
addx -30
addx 12
addx -1
addx 3
addx 1
noop
noop
noop
addx -9
addx 18
addx 1
addx 2
noop
noop
addx 9
noop
noop
noop
addx -1
addx 2
addx -37
addx 1
addx 3
noop
addx 15
addx -21
addx 22
addx -6
addx 1
noop
addx 2
addx 1
noop
addx -10
noop
noop
addx 20
addx 1
addx 2
addx 2
addx -6
addx -11
noop
noop
noop""".splitlines()

graph = create_graph(test_input2)
# pprint(graph)
assert graph[20] == 21
assert graph[60] == 19
assert graph[100] == 18
assert graph[140] == 21
assert graph[180] == 16
assert graph[220] == 18

def signal_strength(graph, max_=220):
    result = 0
    cycle = 20
    for _ in range((max_ - 20)//40 + 1):
        try:
            signal = graph[cycle]
        except:
            print(f"no value forund for {cycle}")
            return result
        # print(cycle, signal, result)
        result += signal * cycle
        cycle += 40
    return result

assert signal_strength(graph) == 13140



```

```{python}
data = read_input("10_input.txt")
graph = create_graph(data)
print(f"{signal_strength(graph)}") # 13720
```

## Day 10 - Part 2

```{python}
def draw_graph(graph, max_=240):
    def is_visible (cycle, val):
        return abs(val - cycle % 40) <= 1
    crt = [["." for _ in range(40)] for _ in range(6)]
    for cycle in range(max_):
        val = graph[cycle+1]
        if is_visible(cycle, val):
            c = "#"
        else:
            c = "."
        # print(cycle, cycle % 40, val, c)
        crt[cycle // 40][cycle % 40] = c
    # pprint(crt)
    return [ "".join(crt[i]) for i in range(6)]

graph = create_graph(test_input2)
# dg = draw_graph(graph)
assert dg == ['##..##..##..##..##..##..##..##..##..##..',
 '###...###...###...###...###...###...###.',
 '####....####....####....####....####....',
 '#####.....#####.....#####.....#####.....',
 '######......######......######......####',
 '#######.......#######.......#######.....']
 
# pprint(dg)


graph = create_graph(data)
pprint(draw_graph(graph))
# pprint(graph)
```

# Day 11

```{python}
test_input = """Monkey 0:
  Starting items: 79, 98
  Operation: new = old * 19
  Test: divisible by 23
    If true: throw to monkey 2
    If false: throw to monkey 3

Monkey 1:
  Starting items: 54, 65, 75, 74
  Operation: new = old + 6
  Test: divisible by 19
    If true: throw to monkey 2
    If false: throw to monkey 0

Monkey 2:
  Starting items: 79, 60, 97
  Operation: new = old * old
  Test: divisible by 13
    If true: throw to monkey 1
    If false: throw to monkey 3

Monkey 3:
  Starting items: 74
  Operation: new = old + 3
  Test: divisible by 17
    If true: throw to monkey 0
    If false: throw to monkey 1""".splitlines()


from attrs import define
from collections.abc import Callable
import re
@define
class Monkey:
    # id: int
    starting_items: list[int]
    operation: str
    divisible: int
    throw: tuple[int, int]

def parse_monkeys(input_):
    monkeys = {}
    id_, starting_items, operation, divisible, true_monkey, false_monkey = None, None, None, None, None, None
    for line in input_:
        if r:=re.search(r'^Monkey ([0-9]+):', line):
            if id_ is not None:
                monkeys[id_] = Monkey(
                    starting_items=starting_items,
                    operation=operation,
                    divisible=divisible,
                    throw=(true_monkey, false_monkey),
                    )
            id_ = int(r[1])
            # print(f"Found Monkey {id_}")
        if r:=re.search(r'Starting items: ([0-9, ]+)', line):
            starting_items =list(map(int, r[1].split(",")))
            # print(f"Found starting items {starting_items}")
        if r:=re.search(r'Operation: new = (.+)', line):
            operation = r[1].strip()
            # print(f"found operation {operation}")
        if r:=re.search(r'Test: divisible by ([0-9]+)', line):
            divisible = int(r[1])
            # print(f"found divisor {divisible}")
        if r:=re.search(r'If true: throw to monkey ([0-9]+)', line):
            true_monkey = int(r[1])
            # print(f"found target if true {true_monkey}")
        if r:=re.search(r'If false: throw to monkey ([0-9]+)', line):
            false_monkey = int(r[1])
            # print(f"found target if false {false_monkey}")
    monkeys[id_] = Monkey(
        starting_items=starting_items,
        operation=operation,
        divisible=divisible,
        throw=(true_monkey, false_monkey),
        )
    
    return monkeys

monkeys=parse_monkeys(test_input)
# pprint(monkeys)
# print(test_input)

from functools import lru_cache
from math import lcm
def one_round(monkeys, relief=True, l=None):

    @lru_cache(maxsize=1_000_000)
    def item_test(item, operation, divisible, relief, l):
        old = item
        new = eval(operation) 
        if relief:
            new = new // 3
        else:
            new = new % l
        return (new % divisible != 0), new
    counts = {}
    for i in range(len(monkeys)):
        m = monkeys[i]
        counts[i] = len(m.starting_items)
        # pprint(m)
        while m.starting_items:
            item = m.starting_items.pop(0)
            test, worry = item_test(item, m.operation, m.divisible, relief, l)
            throw_to=m.throw[test]
            # print(i, item, worry, test, throw_to)
            monkeys[throw_to].starting_items.append(worry)
    return monkeys, counts
            

# for round in range(10):
#     print(f"Round {round+1}")
#     monkeys, _ = one_round(monkeys)
#     pprint(monkeys)

from collections import Counter
from tqdm import tqdm

def activity(monkeys, rounds, relief=True):
    l = lcm(*[m.divisible for m in monkeys.values()])
    total_counts = defaultdict(int)
    for _ in tqdm(range(rounds)):
        monkeys, counts = one_round(monkeys, relief, l)
        for i in range(len(counts)):
            total_counts[i] += counts[i]
    return Counter(total_counts)


def monkey_business(c):
    [a, b] = [_[1] for _ in c.most_common(2)]
    return a*b 

c = activity(monkeys, 20)
print(monkey_business(c))  # 10605

```


```{python}
data = read_input("11_input.txt")
monkeys = parse_monkeys(data)
c = activity(monkeys, 20)
print(monkey_business(c))  # 55930
```

## Day 11 - Part 2

```{python}
monkeys = parse_monkeys(test_input)
counters = {}
for i in range(1, 11):
    c = activity(monkeys, 1000, False)
    counters[i] = c
    print(i, c)
    # pprint(monkeys)

total_counter=sum(counters.values(), start=Counter())
print(total_counter)
print(monkey_business(total_counter)) # 2713310158

```

```{python}
data = read_input("11_input.txt")
monkeys = parse_monkeys(data)

counters = {}
for i in range(1, 11):
    c = activity(monkeys, 1000, False)
    counters[i] = c
    print(i, c)
    # pprint(monkeys)

total_counter=sum(counters.values(), start=Counter())
print(total_counter)
print(monkey_business(total_counter)) # 2713310158

```
# Day 12

```{python}
test_input = """Sabqponm
abcryxxl
accszExk
acctuvwj
abdefghi""".splitlines()

def find_point(data, point="S"):
    for i in range(len(data)):
        if point in data[i]:
            return (i,data[i].index(point))

assert find_point(test_input, "S") == (0,0)
assert find_point(test_input, "E") == (2,5)


def width_height(data):
    width = len(data[0])
    height = len(data)
    return width, height

width, height = width_height(test_input)
# print(width, height)
assert width == 8
assert height == 5

start_pos = find_point(test_input, "S")
end_pos = find_point(test_input, "E")


NAN_VALUE=999
def height_at(data, i, j):
    width, height = width_height(data)
    if ((i < 0) or (i>=height) or (j<0) or (j>=width)):
        return NAN_VALUE
    c = data[i][j]
    if c == "S":
        c = "a"
    if c == "E":
        c = "z"
    return ord(c) - ord("a")

assert height_at(data, *start_pos) == 0
# assert height_at(data, *end_pos) == 25

import networkx as nx

def initialize_graph(data):
    G = nx.DiGraph()
    width, height = width_height(data)
    for i in range(height):
        for j in range(width):
            G.add_node((i,j))
    for i in range(height):
        for j in range(width):
            from_node = (i,j)
            from_height = height_at(data, i, j)
            for (i2, j2) in [(-1, 0), (1, 0), (0, -1), (0, 1)]:
                to_i = i + i2
                to_j = j + j2
                to_height = height_at(data, to_i, to_j)
                if (to_height <= from_height + 1):
                    G.add_edge(from_node, (to_i, to_j))
    return G

G = initialize_graph(test_input)
print(G)
sp = nx.shortest_path(G, start_pos, end_pos)
print(sp, len(sp))
assert len(sp)-1 == 31
print("success")

```


```{python}
data = read_input("12_input.txt")
start_pos = find_point(data, "S")
end_pos = find_point(data, "E")
G = initialize_graph(data)
print(G)
sp = nx.shortest_path(G, start_pos, end_pos)
print("result", len(sp)-1, sp)

# pprint(graph.graph)
```

## Day 12 - Part 2

```{python}
```


# Day 12

```{python}
data = test_input
G = initialize_graph(data)
start_pos = find_point(data, "S")
end_pos = find_point(data, "E")
height_at(data, *end_pos)
print("end", end_pos)
for (i, layer) in enumerate(nx.bfs_layers(G.reverse(), end_pos)):
    for node in layer:
        if height_at(data, *node) == 0:
            print(i, node)
            break

data = read_input("12_input.txt")
G = initialize_graph(data)
start_pos = find_point(data, "S")
end_pos = find_point(data, "E")
height_at(data, *end_pos)
print("end", end_pos)
for (i, layer) in enumerate(nx.bfs_layers(G.reverse(), end_pos)):
    for node in layer:
        if height_at(data, *node) == 0:
            print(i, node)
            break



```

## Day 13

```{python}
test_input = """[1,1,3,1,1]
[1,1,5,1,1]

[[1],[2,3,4]]
[[1],4]

[9]
[[8,7,6]]

[[4,4],4,4]
[[4,4],4,4,4]

[7,7,7,7]
[7,7,7]

[]
[3]

[[[]]]
[[]]

[1,[2,[3,[4,[5,6,7]]]],8,9]
[1,[2,[3,[4,[5,6,0]]]],8,9]
""".splitlines()

data = test_input

# pprint(data)
import json
def parse_data(data):
    data = deepcopy(data)
    pairs = []
    i = 0
    while data:
        line = data.pop(0)
        print("XXX", line, "XXX")
        if line == "":
            continue
        # left = json.loads(data.pop(0))
        left = json.loads(line)
        right = json.loads(data.pop(0))
        pairs.append((left, right))
        i += 2
        print(i, left, right)
        # empty = data.pop(0)
        # print("|", empty, "|")
        # assert empty == ""
    return pairs


def compare(pair):
    """
    1 = yes
    -1 = no
    0 = continue
    """
    left, right = pair
    # print(left, right, type(left), type(right))
    if isinstance(left, int):
        if isinstance(right, int):
            if left < right:
                return 1
            if left > right:
                return -1
            return 0
        assert isinstance(right, list)
        return compare(([left], right))
    assert isinstance(left, list)
    if isinstance(right, int):
        return compare((left, [right]))
    # two lists
    for p in zip(left, right):
        if (r:=compare(p)) != 0:
            return r
    if len(left) <= len(right):
        return 1
    return -1


pairs = parse_data(data) 


assert compare(([2,3,4], 4))
# print(p:=pairs[3])
# print(compare(p))
test_compare = [compare(p) for p in pairs]
# print(test_compare)
assert test_compare == [1, 1, -1, 1, -1, 1, -1, -1]

def main(data):
    pairs = parse_data(data)
    sum = 0
    for i, pair in enumerate(pairs):
        if (r:=compare(pair)) == 1:
            sum += (i + 1)  # The elves have 1-based index
        # print(i, pair, sum, r)
    return sum
print("result", main(data))


print("success")
```


```{python}
data = read_input("13_input.txt")

print(main(data))  # 5760
```

## Day 13 - Part 2

```{python}

data = test_input



markers = [ [[2]], [[6]]]
def parse_single(data):
    packets = []
    for line in data:
        if line == "":
            continue
        packets.append(json.loads(line))
    packets += markers
    return packets

def sort(inp):
    new = []
    for p in inp:
        # print("====")
        # pprint(p)
        new_i = 0
        for q in new:
            pprint(q)
            new_i += 1
            if compare((q, p)) >= 0:
                continue
        print(f"inserting p at {new_i}")
        pprint(new)
        new.insert(new_i, p)
    return new

from functools import cmp_to_key

def comp2(lhs, rhs):
    return compare((lhs, rhs))

def main2(data):
    inp = parse_single(data)
    new = sorted(inp, key=cmp_to_key(comp2), reverse=True)
    result = 1
    for i, p in enumerate(new, start=1):
        if p in markers:
            result *= i
    return result




print(main2(data))

```


```{python}
data = read_input("13_input.txt")

print(main2(data))  # 26670

```

## Day 14

```{python}
test_input = """
""".splitlines()

data = test_input

def main(data):
    result = None
    return result

print(main(data))
print("success")
```

```{python}
data = read_input("14_input.txt")

print("final result", main(data))
```

## Day 14 - Part 2

```{python}

data = test_input

def main2(data):
    result = None
    return result

print("test result", main2(data))

```
```{python}
data = read_input("14_input.txt")

print("final result 2", main2(data))
```


## Day 15

```{python}
test_input = """
""".splitlines()

data = test_input

def main(data):
    result = None
    return result

print(main(data))
print("success")
```

```{python}
data = read_input("15_input.txt")

print("final result", main(data))
```

## Day 15 - Part 2

```{python}

data = test_input

def main2(data):
    result = None
    return result

print("test result", main2(data))

```
```{python}
data = read_input("15_input.txt")

print("final result 2", main2(data))
```
